// const INCREMENT_COUNTER = "INCREMENT_COUNTER";
// const DECREMENT_COUNTER = "DECREMENT_COUNTER";

const type = {
  INCREMENT_COUNTER: "INCREMENT_COUNTER",
  DECREMENT_COUNTER: "DECREMENT_COUNTER",
};

export { type };
